script_key="OrcecGxgZnrjXEJmqRaTrnnbElQRZAMS";
setfpscap(2)

getgenv().gagConfig = {
    -- Event:
    CRAFT_EVENT = { "Enchanted Chest", "Anti Bee Egg" },
    GET_HONEY = true,  -- It will save all pollinated mutation until honey merchant arrives
    BUY_TRAVELING_MERCHANT = { "Bee Egg", "Paradise Egg", "Loquat", "Feijoa", "Pitcher Plant" },
    BUY_EVENT_SHOP = { "Evo Beetroot I", "Evo Blueberry I", "Evo Pumpkin I", "Evo Mushroom I" },
    MAX_EVENT_RESTOCK_SHECKLES = 48000001,
    
    CLAIM_FAIRY_REWARD = { "Mutation Spray Glimmering", "Enchanted Egg", "Enchanted Seed Pack", "FairyPoints" },
    PLANT_EVENT_TREES = true,  -- This config will replace most plant related config
    PLACE_COSMETIC = { "Cooking Kit" },
    
    -- General:
    AUTO_UPDATE_RESTART = true,
    REDEEM_CODES = {},
    EXTRA_PET_SLOTS = 5,
    EXTRA_EGG_SLOTS = 5,
    ADD_FRIEND = true,
    OPEN_ALL_SEED_PACK = true,

    BUY_COSMETIC_SHOP = { ["Cooking Kit"] = 3 },

        MAX_PLANTS = 200,
    DESTROY_UNTIL_MIN_PLANTS = 250,
    DELETE_PLANTS_AFTER_MAX = {
    "Gleamroot", "Tomato", "Corn", "Mango", "Bamboo", "Pepper", 
    "Flare Daisy", "Poseidon Plant", "Duskpuff", "Badlands Pepper", "Mangosteen",
    "Onion", "Dezen", "Jalapeno", "Horsetail", "Amber Spine", "Tall Asparagus",
    "Mushroom", "Lucky Bamboo", "Crown Melon", "Chocolate Carrot", "Wild Carrot",
    "Red Lollipop", "Blue Lollipop", "Stonebite", "Peace Lily", "Mint", "Liberty Lily",
    "Paradise Petal", "Durian", "Papaya", "Moonflower", "Lumira", "Violet Corn",
    "Nectar Thorn", "Cantaloupe", "Aloe Vera", "Firework Flower", "White Mulberry",
    "Dragon Sapling", "Horned Dinoshroom", "Boneboo", "Fruitball", "Enkaku", 
    "Sakura Bush", "Easter Egg", "Eggplant", "Passionfruit", "Lemon", "Moonglow",
    "Blood Banana", "Guanabana", "Nectarine", "Honeysuckle", "Suncoil", "Bendboo", 
    "Cocovine", "Parasol Flower", "Lily Of The Valley", "Firefly Fern", "Moon Mango",
    "Cherry Blossom", "Lotus", "Venus Fly Trap", "Rosy Delight", "Traveler's Fruit", 
    "Noble Flower", "Purple Cabbage", "Sinisterdrip", "Mega Mushroom", 
    "Ice Cream Bean", "Lime", "Crimson Vine", "Zenflare", "Serenity", "Zen Rocks",
    "Pineapple", "Avocado", "Pear", "Apple", "Banana", "Kiwi", "Guava", "Melon",
    "Peach", "Lychee", "Cactus", "Cabbage", "Pumpkin", "Turnip", "Radish", "Beetroot",
    "Broccoli", "Cauliflower", "Spinach", "Lettuce", "Celery", "Cucumber",
    "Bell Pepper", "Chili", "Garlic", "Ginger", "Lotus Root", "Watercress",
    "Rose", "Tulip", "Orchid", "Sunflower", "Daffodil", "Marigold", "Dandelion",
    "Iris", "Carnation", "Poppy", "Snowdrop", "Camellia", "Morning Glory",
    "Hydrangea", "Magnolia", "Wisteria", "Begonia", "Gardenia", "Jasmine"
},
    LIMIT_PLANT_SEED = {
    ["Beanstalk"] = 10,
    ["Sugarglaze"] = 5,
    ["Carrot"] = 5,
    ["Sugar Apple"] = 5,
    ["Hinomai"] = 5,
    ["Grape"] = 5,
    ["Coconut"] = 5,
    ["Dragon Fruit"] = 5,
    ["Ember Lily"] = 5,
    ["Strawberry"] = 5,
    ["Blueberry"] = 5,
    ["Raspberry"] = 5,
    ["Lingonberry"] = 5,
    ["Elder Strawberry"] = 5,
    ["Cactus"] = 2,
    ["Gleamroot"] = 2,
    ["Tomato"] = 2,
    ["Corn"] = 2,
    ["Mango"] = 2,
    ["Bamboo"] = 2,
    ["Pepper"] = 2,
    ["Flare Daisy"] = 2,
    ["Poseidon Plant"] = 2,
    ["Duskpuff"] = 2,
    ["Badlands Pepper"] = 2,
    ["Mangosteen"] = 2,
    ["Onion"] = 2,
    ["Dezen"] = 2,
    ["Jalapeno"] = 2,
    ["Horsetail"] = 2,
    ["Amber Spine"] = 2,
    ["Tall Asparagus"] = 2,
    ["Mushroom"] = 2,
    ["Lucky Bamboo"] = 2,
    ["Crown Melon"] = 2,
    ["Chocolate Carrot"] = 2,
    ["Wild Carrot"] = 2,
    ["Red Lollipop"] = 2,
    ["Blue Lollipop"] = 2,
    ["Stonebite"] = 2,
    ["Peace Lily"] = 2,
    ["Mint"] = 2,
    ["Liberty Lily"] = 2,
    ["Paradise Petal"] = 2,
    ["Durian"] = 2,
    ["Papaya"] = 2,
    ["Moonflower"] = 2,
    ["Lumira"] = 2,
    ["Violet Corn"] = 2,
    ["Nectar Thorn"] = 2,
    ["Cantaloupe"] = 2,
    ["Aloe Vera"] = 2,
    ["Firework Flower"] = 2,
    ["White Mulberry"] = 2,
    ["Dragon Sapling"] = 2,
    ["Horned Dinoshroom"] = 2,
    ["Boneboo"] = 2,
    ["Fruitball"] = 2,
    ["Enkaku"] = 2,
    ["Sakura Bush"] = 2,
    ["Easter Egg"] = 2,
    ["Eggplant"] = 2,
    ["Passionfruit"] = 2,
    ["Lemon"] = 2,
    ["Moonglow"] = 2,
    ["Blood Banana"] = 2,
    ["Guanabana"] = 2,
    ["Nectarine"] = 2,
    ["Honeysuckle"] = 2,
    ["Suncoil"] = 2,
    ["Bendboo"] = 2,
    ["Cocovine"] = 2,
    ["Parasol Flower"] = 2,
    ["Lily Of The Valley"] = 2,
    ["Firefly Fern"] = 2,
    ["Moon Mango"] = 2,
    ["Cherry Blossom"] = 2,
    ["Lotus"] = 2,
    ["Venus Fly Trap"] = 2,
    ["Rosy Delight"] = 2,
    ["Traveler's Fruit"] = 2,
    ["Noble Flower"] = 2,
    ["Purple Cabbage"] = 2,
    ["Sinisterdrip"] = 2,
    ["Mega Mushroom"] = 2,
    ["Ice Cream Bean"] = 2,
    ["Lime"] = 2,
    ["Crimson Vine"] = 2,
    ["Zenflare"] = 2,
    ["Serenity"] = 2,
    ["Zen Rocks"] = 2,
    ["Pineapple"] = 2,
    ["Avocado"] = 2,
    ["Pear"] = 2,
    ["Apple"] = 2,
    ["Banana"] = 2,
    ["Kiwi"] = 2,
    ["Guava"] = 2,
    ["Melon"] = 2,
    ["Peach"] = 2,
    ["Lychee"] = 2,
    ["Cabbage"] = 2,
    ["Pumpkin"] = 2,
    ["Turnip"] = 2,
    ["Radish"] = 2,
    ["Beetroot"] = 2,
    ["Broccoli"] = 2,
    ["Cauliflower"] = 2,
    ["Spinach"] = 2,
    ["Lettuce"] = 2,
    ["Celery"] = 2,
    ["Cucumber"] = 2,
    ["Bell Pepper"] = 2,
    ["Chili"] = 2,
    ["Garlic"] = 2,
    ["Ginger"] = 2,
    ["Lotus Root"] = 2,
    ["Watercress"] = 2,
    ["Rose"] = 2,
    ["Tulip"] = 2,
    ["Orchid"] = 2,
    ["Sunflower"] = 2,
    ["Daffodil"] = 2,
    ["Marigold"] = 2,
    ["Dandelion"] = 2,
    ["Iris"] = 2,
    ["Carnation"] = 2,
    ["Poppy"] = 2,
    ["Snowdrop"] = 2,
    ["Camellia"] = 2,
    ["Morning Glory"] = 2,
    ["Hydrangea"] = 2,
    ["Magnolia"] = 2,
    ["Wisteria"] = 2,
    ["Begonia"] = 2,
    ["Gardenia"] = 2,
    ["Jasmine"] = 2,
    ["Sunbulb"] = 15,
},
    
    BUY_EGGS = { "Jungle Egg", "Anti Bee Egg", "Bug Egg", "Bee Egg", "Paradise Egg", "Mythical Egg", "Rare Summer Egg", "Common Summer Egg", "Rare Egg", "Uncommon Egg" },
    PLANT_EGGS = { "Jungle Egg", "Anti Bee Egg", "Bug Egg", "Paradise Egg", "Zen Egg", "Fall Egg" },
    
    BUY_SEED_SHOP = { "Romanesco", "Elder Strawberry", "Giant Pinecone", "Burning Bud", "Sugar Apple", "Ember Lily", "Beanstalk", "Cacao", "Pepper", "Mushroom", "Grape", "Mango", "Dragon Fruit", "Cactus", ["Coconut"] = 50, ["Bamboo"] = 50, ["Apple"] = 50, ["Pumpkin"] = 50, ["Watermelon"] = 50, ["Daffodil"] = 50, ["Corn"] = 50, ["Tomato"] = 50, ["Orange Tulip"] = 50, ["Blueberry"] = 50, ["Strawberry"] = 50, ["Carrot"] = 50 },
    KEEP_SEEDS = {},
    KEEP_SEEDS_AFTER_MAX_PLANTS = {},
    
    FAVOURITE_FRUIT_MUTATIONS = {},
    SKIP_HARVEST_MUTATIONS = {},

    KEEP_PETS = { "Tiger", "Red Panda", "Barn Owl", "Swan", "Phoenix", "Drake", "Wisp", "Luminous Sprite", "Cockatrice", ["Glimmering Sprite"] = 2, "Gnome", "Griffin", "Golden Goose", "Spriggan", "Junkbot", "Gorilla Chef", "Lobster Thermidor", "French Fry Ferret", "Mochi Mouse", "Corrupted Kitsune", "Raiju", "Mizuchi", "Kitsune", "Koi", "Bald Eagle", "Ankylosaurus", "Spinosaurus", "Brontosaurus", "T-Rex", "Seal", "Fennec Fox", "Disco Bee", "Raccoon", "Queen Bee", "Night Owl", "Dragonfly", "Butterfly", "Mimic Octopus", "Red Fox", "Hyacinth Macaw", "Pack Bee", "Petal Bee", "Bear Bee", "Hamster", "Blood Owl", "Cooked Owl", "Golden Bee", "Owl", "Firefly", "Chicken Zombie", ["Brown Mouse"] = 6, ["Grey Mouse"] = 6, ["Blood Kiwi"] = 2, ["Capybara"] = 1, ["Starfish"] = 2, ["Rooster"] = 8, ["Sunny-Side Chicken"] = 8, ["Tarantula Hawk"] = 5, ["Wasp"] = 5, ["Space Squirrel"] = 3, ["Barn Owl"] = 3, ["Red Panda"] = 8 },
    KEEP_PETS_WEIGHT = 7,
    KEEP_PETS_AGE = 90,

    EQUIP_PETS = { ["Sunny-Side Chicken"] = 8, ["Rooster"] = 8 },
    USE_PETS_FOR_UPGRADE_SLOT = { "Brown Mouse", "Grey Mouse", "Rooster" },
    REMOVE_PET_MAX_UPGRADE = { "Brown Mouse", "Grey Mouse", "Rooster" },  -- Unequip from garden

    BUY_GEAR_SHOP = { "Grandmaster Sprinkler", "Master Sprinkler", "Godly Sprinkler", "Advanced Sprinkler", "Basic Sprinkler", "Trading Ticket", ["Harvest Tool"] = 10 },
    USE_SPRINKLER = { "Basic Sprinkler", "Master Sprinkler", "Godly Sprinkler", "Advanced Sprinkler", "Grandmaster Sprinkler" },

    PET_WEBHOOK_URL = "https://discord.com/api/webhooks/1364042319199731844/dmYoMRg_hJG5HW7M-P_fRMIA7cfU4XskBiCe4kUAwNzlQj4RK_UR28buN2yEIiP0vc-M",
    SEED_WEBHOOK_URL = "https://discord.com/api/webhooks/1364042319199731844/dmYoMRg_hJG5HW7M-P_fRMIA7cfU4XskBiCe4kUAwNzlQj4RK_UR28buN2yEIiP0vc-M", 
    NOTIFY_PETS = { "Tiger", "Swan", "Phoenix", "Cockatrice", "Gnome", "Griffin", "Golden Goose", "Lobster Thermidor", "French Fry Ferret", "Corrupted Kitsune", "Kitsune", "Fennec Fox", "Disco Bee", "Raccoon", "Queen Bee", "Dragonfly", "Butterfly", "Mimic Octopus", "Red Fox", "Brontosaurus", "T-Rex" },
    NOTIFY_PETS_WEIGHT = 7,
    DISCORD_ID = "1344518159587348482",
    WEBHOOK_NOTE = "",
    SHOW_WEBHOOK_USERNAME = true,
    SHOW_WEBHOOK_JOBID = true,

    KICK_AFTER_GIFT_PET = false,
    GIFT_USERNAME = {},
    GIFT_PET = {},
}

loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/c916e5b90dc37c71ecf1ec00dfce3d5d.lua"))()
