setfpscap(5)
script_key="tRdfdNbgjOadczPfrIocaJqMKphaCHoE";
getgenv().UserConfig = {
    ["Auto Buy Seed"] = true,
    ["Auto Plant Seed"] = true,
    ["Limit Plant Seed"] = { -- ["Plant Name"] = Amount
        ["Carrot"] = 5, 
        ["Strawberry"] = 5,
        ["Blueberry"] = 5,
        ["Tulip"] = 5,
        ["Tomato"] = 5,
        ["Apple"] = 5,
        ["Bamboo"] = 0,
        ["Corn"] = 5,
        ["Cactus"] = 5,
        ["Pineangle"] = 5,
        ["Mushroom"] = 0,
        ["Green Bean"] = 0,
        ["Banana"] = 0,
        ["Grape"] = 0,
        ["Coconut"] = 0,
        ["Mango"] = 0,
        ["Dragon Fruit"] = 0,
        ["Acorn"] = 0,
        ["Cherry"] = 0,
        ["Sunflower"] = 0,
        ["Venus Fly Trap"] = 0,
        ["Pomegranate"] = 0,
        ["Poison Apple"] = 0,
    },
    ["Limit Buy Seed"] = { -- ["Seed Name"] = Amount
        ["Carrot"] = 5, 
        ["Strawberry"] = 5,
        ["Blueberry"] = 5,
        ["Tulip"] = 5,
        ["Tomato"] = 5,
        ["Apple"] = 5,
        ["Bamboo"] = 9999,
        ["Corn"] = 5,
        ["Cactus"] = 5,
        ["Pineangle"] = 5,
        ["Mushroom"] = 9999,
        ["Green Bean"] = 5,
        ["Banana"] = 5,
        ["Moon Bloom"] = 50000,
        ["Dragon's Breath"] = 50000,
    },
    ["Favorite"] = {},
    ["Buy Pets"] = { -- ["Pet Name"] = Amount
        ["Monkey"] = 0,
        ["Black Dragon"] = 99,
        ["Golden Dragonfly"] = 99,
        ["Unicorn"] = 0,
        ["Raccoon"] = 99,
        ["Ice Serpent"] = 99,
        ["Deer"] = 5,
    },
    ["Equip Pets"] = { -- {"Pet Name", Amount To Equip, Priority}
        {"Deer", 6, 1},
    },
    ["Expand Plot"] = true,
    ["Plot Expansions"] = 3, -- Max = 5
    ["Unlock Pet Slots"] = 6, -- Max = 6
    ["Auto Collect Seed Packs"] = true,
    ["Gears"] = {
        ["Buy Gear"] = { -- [Gear Name] = Amount
            -- "Common Watering Can",
            "Common Sprinkler",
            "Uncommon Sprinkler",
            "Rare Sprinkler",
            "Legendary Sprinkler",
            "Super Sprinkler",
            "Super Watering Can",
        },
        ["Gears To Use"] = {
            -- "Common Watering Can",
            "Common Sprinkler",
            "Uncommon Sprinkler",
            "Rare Sprinkler",
            "Legendary Sprinkler",
            "Super Sprinkler",
            "Super Watering Can",
        },
    },
    ["Webhook URL"] = "https://discord.com/api/webhooks/1516080485808210104/nVX9SFhS_OHBYIxsQL5HYd5FhRS-YjcwG6kCleOfOHCbR843MoWYVIa_7fCSknSIyU0X",
    ["Webhook Pet Name"] = {},
    ["Webhook Pet Rarity"] = {"Mythic", "Super", "Secret"},
    ["Webhook Note"] = "",
    ["Discord ID"] = "1344518159587348482",
        ["Mail To Username"] = {"Yuri280221"},
        ["Items To Mail"] = {
            ["Pet"] = {
                ["Golden Dragonfly"] = {All = 1, To = "Yuri280221"}, 
                ["Unicorn"] = {All = 1, To = "Yuri280221"},
                ["Raccoon"] = {Normal = 1, Big = 1, Huge = 1, Rainbow = 1, To = "Yuri280221"},
                ["Ice Serpent"] = {All = 1, To = "Yuri280221"}, 
            },
            ["Seed"] = {
                ["Rainbow"] = {Amount = 1, To = "Yuri280221"},
                ["Gold"] = {Amount = 2, To = "Yuri280221"}, 
                ["Bamboo"] = {Amount = 1000, To = "Nilia28022021"},
                ["Mushroom"] = {Amount = 5, To = "Yuri280221"}, 
            },
            ["Gear"] = {
                ["Super Sprinkler"] = 1, 
                ["Super Watering Can"] = {Amount = 1, To = "Yuri280221"}, 
            },
        },
    ["Claim Mail"] = true,
    ["Auto Plant"] = true,
    ["Limit Auto Plant"] = 200,
    ["Blacklist Seed"] = {"Rainbow", "Gold", "Bamboo", "Mushroom", "Dragon's Breath"}
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/66adeacbfb46c0ea4883aefee367292a.lua"))()
