setfpscap(5)
script_key = "tRdfdNbgjOadczPfrIocaJqMKphaCHoE";
getgenv().UserConfig = {
    ["FPS Cap"] = 5,
    ["Auto Buy Seed"] = true,
    ["Auto Plant Seed"] = true,
    ["Limit Plant Seed"] = {
        ["Carrot"] = 2, 
        ["Strawberry"] = 2,
        ["Blueberry"] =2,
        ["Tulip"] = 2,
        ["Tomato"] = 2,
        ["Apple"] = 2,
        ["Bamboo"] = 0,
        ["Corn"] = 30,
        ["Cactus"] = 30,
        ["Pineapple"] = 30,
        ["Mushroom"] = 0,
        ["Green Bean"] = 30,
        ["Banana"] = 30,
        ["Grape"] = 30,
        ["Coconut"] = 30,
        ["Mango"] = 30,
        ["Dragon Fruit"] = 30,
        ["Acorn"] = 20,
        ["Cherry"] = 20,
        ["Sunflower"] = 20,
        ["Venus Fly Trap"] = 20,
        ["Pomegranate"] = 20,
        ["Venom Spitter"] = 50,
        ["Poison Apple"] = 20,
    },
    ["Limit Buy Seed"] = {
        ["Carrot"] = 2, 
        ["Strawberry"] = 2,
        ["Blueberry"] = 2,
        ["Tulip"] = 2,
        ["Tomato"] = 2,
        ["Apple"] = 2,
        ["Bamboo"] = 900,
        ["Corn"] = 5,
        ["Cactus"] = 5,
        ["Pineapple"] = 5,
        ["Mushroom"] = 9999,
        ["Green Bean"] = 5,
        ["Banana"] = 5,
        ["Venom Spitter"] = 9999,
        ["Moon Bloom"] = 50000,
        ["Dragon's Breath"] = 50000,
    },
    ["Favorite"] = {
        ["Horned Melon"] = {""},
    },
    ["Buy Pets"] = {
        ["Frog"] = {Huge = 99, Rainbow = 99}, -- mua 99 Huge, 99 Rainbow (không mua pet Normal, Big)
        ["Bunny"] = {Huge = 99, Rainbow = 99},
        ["Owl"] = {Huge = 99, Rainbow = 99},
        ["Deer"] = {Huge = 99, Rainbow = 99},
        ["Robin"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Bee"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Monkey"] = 999, -- mua 999 tất cả loại
        ["Bear"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Golden Dragonfly"] = 999,
        ["Unicorn"] = 999,
        ["Raccoon"] = 999,
        ["Black Dragon"] = 999,
    },
    ["Equip Pets"] = {
        {"Bunny", 6, 1},
    },
    ["Expand Plot"] = true,
    ["Plot Expansions"] = 3,
    ["Unlock Pet Slots"] = 5,
    ["Auto Collect Seed Packs"] = true,
    ["Gears"] = {
        ["Buy Gear"] = {
            "Super Sprinkler",
            "Legendary Sprinkler",
            "Super Watering Can",
        },
        ["Gears To Use"] = {},
    },
    ["Webhook URL"] = "https://discord.com/api/webhooks/1516080485808210104/nVX9SFhS_OHBYIxsQL5HYd5FhRS-YjcwG6kCleOfOHCbR843MoWYVIa_7fCSknSIyU0X",
    ["Webhook Pet Name"] = {"Golden Dragonfly","Unicorn","Raccoon"},
    ["Webhook Pet Rarity"] = {"Mythic", "Super", "Secret"},
    ["Webhook Seed Name"] = {""},
    ["Webhook Note"] = "",
    ["Discord ID"] = "xxx",
    ["Mail To Username"] = {"Yuri280221"},
    ["Items To Mail"] = {
        ["Pet"] = {
            ["Golden Dragonfly"] = 1,
            ["Unicorn"] = 1,
            ["Raccoon"] = 1,
            ["Monkey"] = 1,
            ["Bear"] = 1,
            ["Ice Serpent"] = 1,
        },
        ["Seed"] = {
            ["Rainbow"] = 1,
            ["Gold"] = 2,
            ["Mushroom"] = 10,
            ["Bamboo"] = 50,
        },
        ["Gear"] = {
            ["Legendary Sprinkler"] = 1,
            ["Super Sprinkler"] = 1,
            ["Super Watering Can"] = 1,
        },
    },
    ["Claim Mail"] = true,
    ["Auto Plant"] = true,
    ["Limit Auto Plant"] = 600,
    ["Blacklist Seed"] = {"Rainbow", "Gold", "Dragon's Breath"}
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/66adeacbfb46c0ea4883aefee367292a.lua"))()
